export const LABS=[['trace','Python trace','Python追踪','2.1'],['sorting','Sorting studio','排序工作室','4.3'],['binary','Binary search','二分查找','4.2'],['graph','Graph explorer','图搜索','4.4'],['vectors','Vectors & matrices','向量与矩阵','3.4'],['probability','Probability & Bayes','概率与贝叶斯','3.5'],['regression','Fit a line','拟合直线','6.1'],['gradient','Gradient descent','梯度下降','6.6'],['knn','Nearest neighbors','最近邻','6.2'],['kmeans','K-means clustering','K-means聚类','6.3'],['neuron','Inside a neuron','神经元内部','6.5'],['convolution','Convolution & pooling','卷积与池化','6.8']];
export function numbers(text,min=1,max=20){const a=String(text).trim().split(/[\s,，]+/).map(Number);if(a.length<min||a.length>max||a.some(x=>!Number.isFinite(x)||Math.abs(x)>10000))throw new Error('numbers');return a;}
export function metrics(tp,fp,fn,tn){const total=tp+fp+fn+tn;return {accuracy:total?(tp+tn)/total:null,precision:tp+fp?tp/(tp+fp):null,recall:tp+fn?tp/(tp+fn):null};}
export function sortingFrames(values,mode='bubble'){
 const a=[...values],frames=[{values:[...a],indices:[]}];const snap=(indices)=>frames.push({values:[...a],indices});
 if(mode==='bubble'){for(let end=a.length-1;end>0;end--)for(let j=0;j<end;j++){if(a[j]>a[j+1])[a[j],a[j+1]]=[a[j+1],a[j]];snap([j,j+1]);}}
 if(mode==='selection'){for(let i=0;i<a.length-1;i++){let j=i;for(let k=i+1;k<a.length;k++)if(a[k]<a[j])j=k;[a[i],a[j]]=[a[j],a[i]];snap([i,j]);}}
 if(mode==='insertion'){for(let i=1;i<a.length;i++){const x=a[i];let j=i-1;while(j>=0&&a[j]>x){a[j+1]=a[j];j--;}a[j+1]=x;snap([j+1,i]);}}
 if(mode==='merge'){const merge=(l,r)=>{if(r-l<2)return;const m=Math.floor((l+r)/2);merge(l,m);merge(m,r);const left=a.slice(l,m),right=a.slice(m,r),joined=[];while(left.length&&right.length)joined.push(left[0]<=right[0]?left.shift():right.shift());joined.push(...left,...right);a.splice(l,r-l,...joined);snap(Array.from({length:r-l},(_,i)=>l+i));};merge(0,a.length);}
 return frames;
}
export function binaryFrames(values,target){if(values.some((v,i)=>i&&v<values[i-1]))throw new Error('sorted');let lo=0,hi=values.length-1,frames=[];while(lo<=hi){const mid=Math.floor((lo+hi)/2);frames.push({lo,hi,mid,found:values[mid]===target});if(values[mid]===target)return frames;if(values[mid]<target)lo=mid+1;else hi=mid-1;}frames.push({lo,hi,mid:-1,found:false});return frames;}
export function traverse(edges,start,mode){const graph={};for(const [a,b] of edges){(graph[a]??=[]).push(b);graph[b]??=[];}for(const ns of Object.values(graph))ns.sort();const seen=new Set(),order=[];if(mode==='dfs'){const visit=n=>{seen.add(n);order.push(n);for(const v of graph[n]||[])if(!seen.has(v))visit(v);};visit(start);}else{const queue=[start];seen.add(start);while(queue.length){const n=queue.shift();order.push(n);for(const v of graph[n]||[])if(!seen.has(v)){seen.add(v);queue.push(v);}}}return order;}
export function convolution(input,kernel,stride=1,padding=0){const n=input.length,k=kernel.length,out=Math.floor((n+2*padding-k)/stride)+1;if(out<1)throw new Error('shape');return Array.from({length:out},(_,i)=>Array.from({length:out},(_,j)=>{let sum=0;for(let a=0;a<k;a++)for(let b=0;b<k;b++)sum+=(input[i*stride+a-padding]?.[j*stride+b-padding]??0)*kernel[a][b];return sum;}));}
export function kmeansStep(points,centers){const groups=centers.map(()=>[]);points.forEach(x=>{let i=0;centers.forEach((c,j)=>{if(Math.abs(x-c)<Math.abs(x-centers[i]))i=j;});groups[i].push(x);});return {groups,centers:centers.map((c,i)=>groups[i].length?groups[i].reduce((a,b)=>a+b,0)/groups[i].length:c)};}
export const labState={id:'trace',step:0,params:{}};
const defaults={trace:{start:'4',increment:'3',multiplier:'2'},sorting:{values:'4, 1, 7, 3, 5',mode:'bubble'},binary:{values:'2, 4, 6, 8, 10, 12, 14',target:'10'},graph:{edges:'A-B, A-D, B-C, C-A, C-E, D-E, E-F, F-B',start:'A',mode:'bfs'},vectors:{a:'1, 2',b:'3, 4',matrix:'1, 2, 3, 4'},probability:{red:'2',white:'2',prior:'1',sensitivity:'90',falsePositive:'10'},regression:{slope:'1',bias:'0'},gradient:{start:'0',rate:'0.1'},knn:{points:'2,1,R; 0,2,B; 3,4,B; 5,2,R; 2,6,R',x:'2',y:'2',k:'3'},kmeans:{values:'1, 2, 8, 9',centers:'1, 9'},neuron:{x1:'-1',x2:'2',w1:'2',w2:'1',bias:'-1',activation:'relu'},convolution:{input:'1,2,3,4,5,6,7,8,9',kernel:'1,0,0,-1',stride:'1',padding:'0'},metrics:{tp:'16',fp:'8',fn:'4',tn:'72'}};
LABS.push(['metrics','Model scorecard','模型评分','5.4']);
export function resetLab(id){labState.id=id;labState.step=0;labState.params={...defaults[id]};}
export function renderLab(id,b,esc){if(labState.id!==id||!Object.keys(labState.params).length)resetLab(id);const p=labState.params;const val=k=>esc(p[k]);const field=(key,en,zh,type='text',min,max)=>`<label>${b(en,zh)}<input data-lab-param="${key}" value="${val(key)}" type="${type}" ${min!==undefined?`min="${min}" max="${max}"`:''}></label>`;const select=(key,en,zh,opts)=>`<label>${b(en,zh)}<select data-lab-param="${key}">${opts.map(([v,a,c])=>`<option value="${v}" ${p[key]===v?'selected':''}>${b(a,c)}</option>`).join('')}</select></label>`;let inputs='',visual='',output='',help='',maxStep=0;const f=x=>Number(x.toFixed(4));const cells=(a,hot=[])=>`<div class="cells">${a.map((v,i)=>`<span class="cell ${hot.includes(i)?'hot':''}">${esc(v)}</span>`).join('')}</div>`;const svg=(inner)=>`<svg viewBox="0 0 400 240" role="img" aria-label="${esc(b('Interactive result; full values follow below.','交互结果，完整数值见下方。'))}">${inner}</svg>`;const point=(x,y,color='var(--teal)')=>`<circle cx="${40+x*45}" cy="${210-y*25}" r="6" fill="${color}"/>`;
 try{
 if(id==='trace'){inputs=field('start','Starting count','初始count','number',-100,100)+field('increment','Increment','增加量','number',-100,100)+field('multiplier','Multiplier','乘数','number',-10,10);maxStep=3;const start=+p.start,inc=+p.increment,mul=+p.multiplier,count=labState.step>=2?start+inc:start;visual=`<pre class="lab-output">${esc(`count = ${start}\ncount = count + ${inc}\ntotal = count * ${mul}`)}</pre>`;output=labState.step===0?b('Before execution: no variables assigned.','执行前：尚未赋值。'):`count = ${count}${labState.step>=3?`\ntotal = ${count*mul}`:''}`;help=b('Each step executes one line. Read the right side using the current value, then update the name.','每步执行一行。用当前值计算右侧，再更新名字。');}
 if(id==='sorting'){inputs=field('values','Values (comma-separated)','数值（逗号分隔）')+select('mode','Algorithm','算法',[['bubble','Bubble','冒泡'],['selection','Selection','选择'],['insertion','Insertion','插入'],['merge','Merge','归并']]);const a=numbers(p.values);const frames=sortingFrames(a,p.mode);maxStep=frames.length-1;const frame=frames[Math.min(labState.step,maxStep)],scale=Math.max(...a.map(Math.abs),1);visual=`<div class="bars">${frame.values.map((v,i)=>`<div class="bar ${frame.indices.includes(i)?'hot':''}" style="height:${Math.max(20,Math.abs(v)/scale*160)}px">${v}</div>`).join('')}</div>`;output=`[${frame.values.join(', ')}]\n${b('Highlighted positions','高亮位置')}: ${frame.indices.join(', ')||'—'}`;help=b('Step through comparisons or completed insertion/selection/merge stages. Bar height shows absolute magnitude; labels preserve signs.','逐步观察比较或插入、选择、归并阶段。条高表示绝对值，标签保留正负号。');}
 if(id==='binary'){inputs=field('values','Sorted values','有序数值')+field('target','Target','目标','number',-10000,10000);const a=numbers(p.values),frames=binaryFrames(a,+p.target);maxStep=frames.length-1;const r=frames[Math.min(labState.step,maxStep)];visual=cells(a,[r.mid]);output=r.mid<0?b('Empty interval: target not found.','区间为空：未找到目标。'):`lo=${r.lo}, hi=${r.hi}, mid=${r.mid}, value=${a[r.mid]}\n${r.found?b('Target found.','找到目标。'):b('Compare, then discard the impossible half.','比较后排除不可能的一半。')}`;help=b('Binary search requires sorted input. lo and hi are inclusive indices.','二分要求输入有序。lo与hi为包含端点的索引。');}
 if(id==='graph'){inputs=field('edges','Directed edges (A-B, B-C)','有向边（A-B, B-C）')+field('start','Start vertex','起点')+select('mode','Traversal','遍历',[['bfs','BFS · queue','BFS · 队列'],['dfs','DFS · recursion','DFS · 递归']]);const edges=p.edges.split(',').map(s=>s.trim().split('-'));if(edges.length>30||edges.some(e=>e.length!==2||e.some(n=>! /^[A-Z]$/.test(n)))||! /^[A-Z]$/.test(p.start))throw Error();const nodes=[...new Set(edges.flat())].sort();if(nodes.length>12||!nodes.includes(p.start))throw Error();const order=traverse(edges,p.start,p.mode);maxStep=order.length;const shown=order.slice(0,labState.step);const pos=Object.fromEntries(nodes.map((n,i)=>[n,[200+90*Math.cos(i*2*Math.PI/nodes.length),120+85*Math.sin(i*2*Math.PI/nodes.length)]]));visual=svg(`<defs><marker id="arrow" markerWidth="6" markerHeight="6" refX="14" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" fill="var(--muted)"/></marker></defs>${edges.map(([a,c])=>`<line x1="${pos[a][0]}" y1="${pos[a][1]}" x2="${pos[c][0]}" y2="${pos[c][1]}" stroke="var(--muted)" marker-end="url(#arrow)"/>`).join('')}${nodes.map(n=>`<circle cx="${pos[n][0]}" cy="${pos[n][1]}" r="17" fill="${shown.includes(n)?'var(--lime)':'var(--paper)'}" stroke="var(--teal)"/><text x="${pos[n][0]}" y="${pos[n][1]+4}" text-anchor="middle">${n}</text>`).join('')}`);output=b('Discovered: ','已发现：')+(shown.join(' → ')||'—');help=b('Neighbors are processed alphabetically; mark on discovery to prevent cycles from repeating.','邻居按字母顺序处理，发现时标记以避免环中重复。');}
 if(id==='vectors'){inputs=field('a','Vector A (2 values)','向量A（2个值）')+field('b','Vector B (2 values)','向量B（2个值）')+field('matrix','2×2 matrix, row order','2×2矩阵，按行');const a=numbers(p.a,2,2),c=numbers(p.b,2,2),m=numbers(p.matrix,4,4);const dot=a[0]*c[0]+a[1]*c[1],sum=a.map((v,i)=>v+c[i]),product=[m[0]*a[0]+m[1]*a[1],m[2]*a[0]+m[3]*a[1]];visual=cells([`A=[${a}]`,`B=[${c}]`,`M=[${m.slice(0,2)}; ${m.slice(2)}]`]);output=`A+B=[${sum}]\nA·B=${dot}\nM@A=[${product}]\n${b('Distance','距离')}=${f(Math.hypot(a[0]-c[0],a[1]-c[1]))}`;help=b('Addition combines matching components. Dot products sum products. Matrix multiplication combines each row with the vector.','加法合并对应分量，点积对乘积求和，矩阵乘法用每一行与向量计算。');}
 if(id==='probability'){inputs=field('red','Red balls','红球','number',0,100)+field('white','White balls','白球','number',0,100)+field('prior','Prevalence (%)','发生率（%）','number',0,100)+field('sensitivity','Sensitivity (%)','灵敏度（%）','number',0,100)+field('falsePositive','False-positive (%)','假阳性率（%）','number',0,100);const r=+p.red,w=+p.white;if(!Number.isInteger(r)||!Number.isInteger(w)||r<0||w<0||r+w<2)throw Error();const prior=+p.prior/100,sens=+p.sensitivity/100,fp=+p.falsePositive/100;if([prior,sens,fp].some(x=>x<0||x>1))throw Error();const denom=prior*sens+(1-prior)*fp;const prob=r<2?0:r/(r+w)*(r-1)/(r+w-1);visual=cells([`${b('Red','红球')}: ${r}`,`${b('White','白球')}: ${w}`]);output=`${b('Two reds without replacement','不放回抽两红')}: ${f(prob)}\n${b('Two reds with replacement','放回抽两红')}: ${f((r/(r+w))**2)}\nP(${b('condition | positive test','状态 | 检测阳性')}) = ${denom?f(prior*sens/denom*100)+'%':b('undefined','未定义')}`;help=b('Without replacement the second probability changes. Bayes also accounts for the base rate and false positives.','不放回时第二次概率改变。贝叶斯还考虑基础发生率与假阳性。');}
 if(id==='regression'){inputs=field('slope','Slope w','斜率w','number',-10,10)+field('bias','Bias b','偏置b','number',-10,10);const w=+p.slope,c=+p.bias,data=[[1,2],[2,3],[3,5],[4,4],[5,6]],pred=data.map(([x])=>w*x+c),mse=pred.reduce((s,y,i)=>s+(y-data[i][1])**2,0)/data.length;visual=svg(`<line x1="40" y1="210" x2="350" y2="210" class="line"/><line x1="40" y1="210" x2="40" y2="10" class="line"/>${data.map(([x,y])=>point(x,y)).join('')}<line x1="40" y1="${210-c*25}" x2="310" y2="${210-(w*6+c)*25}" stroke="var(--indigo)" stroke-width="2"/>`);output=`ŷ=${w}x+${c}\n${b('Predictions','预测')}: [${pred.map(f)}]\nMSE=${f(mse)}`;help=b('Adjust the line to reduce squared residuals. Data points are (1,2),(2,3),(3,5),(4,4),(5,6).','调节直线以减小残差平方。数据点为(1,2),(2,3),(3,5),(4,4),(5,6)。');}
 if(id==='gradient'){inputs=field('start','Initial w','初始w','number',-10,10)+field('rate','Learning rate η','学习率η','number',0,2);maxStep=20;const rate=+p.rate;if(rate<=0||rate>2)throw Error();let w=+p.start,trail=[w];for(let i=0;i<labState.step;i++){w-=rate*2*(w-3);trail.push(w);}const grad=2*(w-3);visual=svg(`<polyline points="${Array.from({length:61},(_,i)=>{const x=i/10;return `${40+x*45},${210-(x-3)**2*18}`;}).join(' ')}" fill="none" stroke="var(--teal)" stroke-width="2"/><circle cx="${40+w*45}" cy="${210-(w-3)**2*18}" r="7" fill="var(--indigo)"/>`);output=`L(w)=(w-3)²\nw=${f(w)}, ∇L=${f(grad)}, L=${f((w-3)**2)}\n${b('History','历史')}: ${trail.map(f).join(' → ')}`;help=b('Each step applies w←w-η·2(w-3). Rates above 1 cause divergence for this loss; values may leave the plot.','每步执行w←w-η·2(w-3)。此损失学习率大于1会发散，数值可能超出图范围。');}
 if(id==='knn'){inputs=field('points','Samples: x,y,R or B; separate with ;','样本：x,y,R或B；用;分隔')+field('x','Query x','查询x','number',-10,10)+field('y','Query y','查询y','number',-10,10)+field('k','K','K','number',1,10);const ps=p.points.split(';').map(s=>s.trim().split(','));if(ps.length>12||ps.some(a=>a.length!==3||!['R','B'].includes(a[2])||a.slice(0,2).some(v=>!Number.isFinite(+v))))throw Error();const k=+p.k;if(!Number.isInteger(k)||k<1||k>ps.length)throw Error();const nearest=ps.map((a,i)=>({i,x:+a[0],y:+a[1],label:a[2],d:Math.hypot(+a[0]-p.x,+a[1]-p.y)})).sort((a,c)=>a.d-c.d||a.i-c.i).slice(0,k),red=nearest.filter(a=>a.label==='R').length,blue=k-red;visual=svg(ps.map(a=>point(+a[0],+a[1],a[2]==='R'?'#b75949':'#536cab')).join('')+point(+p.x,+p.y,'var(--text)'));output=nearest.map(a=>`${a.i+1}: ${a.label}, d=${f(a.d)}`).join('\n')+`\n${b('Prediction','预测')}: ${red===blue?b('tie (choose another K)','平票（可调整K）'):red>blue?b('red','红'):b('blue','蓝')}`;help=b('Vote among the K closest points. Equal-distance ties use sample order; a vote tie is reported rather than hidden.','最近K点投票。距离相同按样本顺序，投票平局明确报告。');}
 if(id==='kmeans'){inputs=field('values','1D samples','一维样本')+field('centers','Initial centers','初始中心');const points=numbers(p.values),initial=numbers(p.centers,1,5);maxStep=12;let centers=initial,r=kmeansStep(points,centers);for(let i=0;i<labState.step;i++){centers=r.centers;r=kmeansStep(points,centers);}visual=cells(r.groups.map((g,i)=>`C${i}: [${g}]`));output=`${b('Centers after update','更新后中心')}: [${r.centers.map(f)}]\n${b('Squared-distance sum','平方距离和')}: ${f(r.groups.reduce((s,g,i)=>s+g.reduce((v,x)=>v+(x-r.centers[i])**2,0),0))}`;help=b('Each step reassigns points then averages each group. Empty groups keep the old center. Equal distances use the earlier center. Cluster IDs are not rankings.','每步重新分配后取组均值。空组保留旧中心，等距取前一个中心。簇编号不是排名。');}
 if(id==='neuron'){inputs=['x1','x2','w1','w2'].map(k=>field(k,k,k,'number',-10,10)).join('')+field('bias','Bias','偏置','number',-10,10)+select('activation','Activation','激活',[['relu','ReLU','ReLU'],['sigmoid','Sigmoid','Sigmoid'],['linear','Linear','线性']]);const z=+p.x1*p.w1+(+p.x2*p.w2)+(+p.bias),h=p.activation==='relu'?Math.max(0,z):p.activation==='sigmoid'?1/(1+Math.exp(-z)):z;visual=cells([`x₁·w₁=${f(p.x1*p.w1)}`,`x₂·w₂=${f(p.x2*p.w2)}`,`b=${p.bias}`,`z=${f(z)}`,`h=${f(h)}`]);output=`z=w₁x₁+w₂x₂+b=${f(z)}\nh=${f(h)}`;help=b('Combine weighted inputs and bias first, then apply the selected activation. A linear output keeps negative values.','先结合加权输入与偏置，再应用所选激活。线性输出保留负值。');}
 if(id==='convolution'){inputs=field('input','3×3 input (9 values)','3×3输入（9值）')+field('kernel','2×2 kernel (4 values)','2×2核（4值）')+field('stride','Stride','步幅','number',1,3)+field('padding','Padding','填充','number',0,2);const a=numbers(p.input,9,9),k=numbers(p.kernel,4,4),stride=+p.stride,pad=+p.padding;if(!Number.isInteger(stride)||stride<1||stride>3||!Number.isInteger(pad)||pad<0||pad>2)throw Error();const out=convolution([a.slice(0,3),a.slice(3,6),a.slice(6)], [k.slice(0,2),k.slice(2)],stride,pad),flat=out.flat();maxStep=flat.length;visual=cells(flat,labState.step?[Math.min(labState.step-1,flat.length-1)]:[]);output=`${b('Output rows','输出行')}:\n${out.map(r=>'['+r.join(', ')+']').join('\n')}\n${b('Global max pooling','全局最大池化')}: ${Math.max(...flat)}\n${b('Global average pooling','全局平均池化')}: ${f(flat.reduce((s,x)=>s+x,0)/flat.length)}`;help=b('CNN-style cross-correlation: the kernel is not flipped. Padding uses zero; bias is zero here. Step highlights each output location. Pooling summarizes the full output in this lab.','CNN式互相关：不翻转核，填充为0，本例偏置为0。步进高亮各输出位置。此实验对完整输出做池化。');}
 if(id==='metrics'){inputs=field('tp','True positive TP','真正例TP','number',0,10000)+field('fp','False positive FP','假正例FP','number',0,10000)+field('fn','False negative FN','假负例FN','number',0,10000)+field('tn','True negative TN','真负例TN','number',0,10000);const vs=['tp','fp','fn','tn'].map(k=>+p[k]);if(vs.some(x=>x<0||!Number.isInteger(x)))throw Error();const r=metrics(...vs);visual=cells([`TP=${p.tp}`,`FP=${p.fp}`,`FN=${p.fn}`,`TN=${p.tn}`]);output=Object.entries(r).map(([k,v])=>`${b({accuracy:'Accuracy',precision:'Precision',recall:'Recall'}[k],{accuracy:'准确率',precision:'精确率',recall:'召回率'}[k])}: ${v===null?b('undefined (zero denominator)','未定义（分母为零）'):f(v*100)+'%'}`).join('\n');help=b('Define a positive class first. Accuracy counts all correct decisions; precision looks at predicted positives; recall looks at actual positives.','先定义正类。准确率统计全部正确判断；精确率看预测正类，召回率看实际正类。');}
 if(Object.values(p).some(x=>typeof x!=='string'||x.length>1000)||Object.entries(p).some(([k,x])=>!['values','mode','edges','start','a','b','matrix','points','centers','input','kernel','activation'].includes(k)&&!Number.isFinite(+x)))throw Error();
 }catch{visual='';output=b('Check the input: use finite numbers, valid sizes and the specified format. Binary-search values must be sorted.','请检查输入：使用有限数值、正确大小与指定格式。二分查找数值必须有序。');maxStep=0;}
 const title=LABS.find(x=>x[0]===id)||LABS[0];return `<div class="welcome"><div class="eyebrow">${b('Experiment • understand • explain','实验 · 理解 · 解释')}</div><h1>${b(title[1],title[2])}</h1><p class="muted">${help}</p></div><div class="card"><div class="lab-inputs">${inputs}</div><div class="flex wrap section"><button data-action="lab-reset">↺ ${b('Reset','重置')}</button>${maxStep?`<button data-action="lab-back" ${labState.step<=0?'disabled':''}>← ${b('Back','上一步')}</button><button class="primary" data-action="lab-step" ${labState.step>=maxStep?'disabled':''}>${b('Step','下一步')} →</button><span class="small muted">${Math.min(labState.step,maxStep)} / ${maxStep}</span>`:''}<a class="button" href="#lesson/${title[3]}">${b('Related lesson','相关课程')} ↗</a></div><div class="lab-canvas">${visual}</div><h3>${b('What happened?','发生了什么？')}</h3><pre class="lab-output" aria-live="polite">${esc(output)}</pre></div>`;
}
