export const EXERCISES=[
 {id:'basics',title:{en:'Input, loops & totals',zh:'输入、循环与总和'},instructions:{en:'Read an integer n, add the integers from 1 through n, and print the total. Try input 5: the expected output is 15.',zh:'读入整数n，累加1到n并打印总和。输入5时应输出15。'},hint:{en:'input() returns text. Use int(), initialize total=0 and include n with range(1,n+1).',zh:'input()返回文本，用int()转换。初始化total=0，用range(1,n+1)包含n。'},input:'5',code:'n = int(input())\ntotal = 0\nfor value in range(1, n + 1):\n    # Add value to total here\n    pass\nprint(total)\n',packages:[]},
 {id:'functions',title:{en:'Write a reusable mean',zh:'编写可复用均值函数'},instructions:{en:'Implement mean(values). Return the sum divided by the count; return None for an empty list. Expected output: 4.0 then None.',zh:'实现mean(values)。返回总和除以数量，空列表返回None。应依次输出4.0与None。'},hint:{en:'Handle the empty list before dividing. return gives a value back; print belongs to the caller.',zh:'先处理空列表，再除法。return交回值，由调用者print。'},input:'',code:'def mean(values):\n    # Replace this placeholder\n    return None\n\nprint(mean([2, 4, 6]))\nprint(mean([]))\n',packages:[]},
 {id:'numpy',title:{en:'Explore array axes',zh:'探索数组轴'},instructions:{en:'Predict both sums before running. Then change axis or a matrix element and explain the new shape and values.',zh:'运行前预测两个求和结果，再改变axis或矩阵元素并解释新形状与数值。'},hint:{en:'axis=0 collapses the row dimension, producing column sums [4,6]. axis=1 produces row sums [3,7].',zh:'axis=0消去行维度，得到列和[4,6]；axis=1得到行和[3,7]。'},input:'',code:'import numpy as np\na = np.array([[1, 2], [3, 4]])\nprint("shape:", a.shape)\nprint("axis 0:", a.sum(axis=0))\nprint("axis 1:", a.sum(axis=1))\n',packages:['numpy']},
 {id:'pandas',title:{en:'Clean a small table',zh:'清洗小表格'},instructions:{en:'Inspect the missing reading. Fill it using the mean of the available values. Explain why fitting on test data would be inappropriate in a model workflow.',zh:'检查缺失值，用已有值均值填补，解释模型流程中为什么不应在测试数据上拟合。'},hint:{en:'The observed values 2 and 6 have mean 4. Use fillna; preserve a record of which values were missing.',zh:'已有值2和6的均值为4。使用fillna，并保留缺失位置的记录。'},input:'',code:'import pandas as pd\ndf = pd.DataFrame({"reading": [2, None, 6]})\nprint(df)\ntraining_mean = df["reading"].mean()\ndf["reading"] = df["reading"].fillna(training_mean)\nprint(df)\n',packages:['pandas']},
 {id:'plot',title:{en:'Make a clear scatter plot',zh:'绘制清晰散点图'},instructions:{en:'Run the plot, then add a title and explain what the data can and cannot establish about study time and score.',zh:'运行图表，再加标题并解释数据能说明及不能说明的学习时间与成绩关系。'},hint:{en:'An association is not proof of causation. Keep axis labels and units.',zh:'关联不证明因果。保留轴标签与单位。'},input:'',code:'import matplotlib.pyplot as plt\nminutes = [10, 20, 30, 40, 50]\nscores = [50, 60, 58, 75, 80]\nplt.scatter(minutes, scores)\nplt.xlabel("Study time (minutes)")\nplt.ylabel("Score")\nplt.tight_layout()\nplt.show()\n',packages:['matplotlib']},
 {id:'model',title:{en:'Train a small regression',zh:'训练小型回归'},instructions:{en:'Fit a linear model to x→2x+1. Predict at x=5, then change one training label and inspect the coefficients.',zh:'拟合x→2x+1，在x=5处预测。再改变一个训练标签并观察系数。'},hint:{en:'X needs two dimensions. Training should recover slope≈2 and bias≈1, predicting≈11.',zh:'X需要二维。训练应恢复斜率约2、偏置约1，预测约11。'},input:'',code:'import numpy as np\nfrom sklearn.linear_model import LinearRegression\nX = np.array([[1], [2], [3], [4]])\ny = np.array([3, 5, 7, 9])\nmodel = LinearRegression().fit(X, y)\nprint("slope:", model.coef_)\nprint("bias:", model.intercept_)\nprint("prediction:", model.predict([[5]]))\n',packages:['scikit-learn']}
];
let worker=null,runId=0;
export const pythonView={status:'idle',output:'',plots:[],hint:false};
export function stopPython(){worker?.terminate();worker=null;runId++;pythonView.status='stopped';}
export function runPython(exercise,code,input,update){if(pythonView.status==='loading'||pythonView.status==='running')return;pythonView.status='loading';pythonView.output='';pythonView.plots=[];const id=++runId;worker??=new Worker(new URL('./python-worker.js',import.meta.url),{type:'module'});worker.onmessage=({data})=>{if(id!==runId)return;if(data.type==='status')pythonView.status=data.status;if(data.type==='stdout')pythonView.output+=data.text+'\n';if(data.type==='error'){pythonView.output+=data.message;pythonView.status='error';}if(data.type==='done'){pythonView.status='done';pythonView.plots=data.plots;}update();};worker.onerror=e=>{if(id!==runId)return;pythonView.status='error';pythonView.output=e.message||'Python worker could not start.';worker?.terminate();worker=null;update();};worker.postMessage({code,input,packages:exercise.packages});update();}
