import test from 'node:test';
import {Worker} from 'node:worker_threads';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {defaults,grade,sameAnswer,recordResponse,reviewNext,expired,mastery,validateState,decodeBackup,encodeBackup,DAY,diagnosticQuestions} from '../js/core.js';
import {createStore} from '../js/store.js';
import {metrics,sortingFrames,binaryFrames,traverse,convolution,kmeansStep,numbers} from '../js/labs.js';
const curriculum=JSON.parse(readFileSync(new URL('../data/curriculum.json',import.meta.url))),exams=JSON.parse(readFileSync(new URL('../data/exams.json',import.meta.url)));
const questions=new Map([...curriculum.questions,...exams.questions].map(q=>[q.id,q]));const ids={lessons:new Set(curriculum.lessons.map(l=>l.id)),questions};
function attempt(kind='practice',qids=['drill-1.1-1']){return {id:'test-attempt',kind,title:{en:'Test',zh:'测试'},questionIds:qids,index:0,answers:{},flags:{},graded:{},startedAt:100,deadline:kind==='exam'?100+90*60000:null,submittedAt:null};}
test('all 38 sections and 114 authored checks have complete bilingual content and valid references',()=>{
 assert.equal(curriculum.lessons.length,38);assert.equal(curriculum.questions.length,114);assert.equal(new Set(questions.keys()).size,192);
 for(const l of curriculum.lessons){for(const key of ['title','body','example','mistake','skill'])for(const lang of ['en','zh'])assert.ok(l[key][lang].length>1,`${l.id} ${key} ${lang}`);assert.ok(l.prerequisites.every(id=>ids.lessons.has(id)));assert.equal(l.questionIds.length,3);assert.ok(l.questionIds.every(id=>questions.has(id)));assert.equal(l.source.section,l.id);assert.equal(l.license,'CC-BY-NC-SA-4.0');assert.ok(l.page>=5&&l.page<=233);for(const o of l.objectives)assert.ok(o.en&&o.zh);}
 for(const q of questions.values()){assert.ok(q.prompt.en&&q.prompt.zh&&q.explanation.en&&q.explanation.zh,q.id);assert.ok(q.options.every(o=>o.en&&o.zh));assert.ok(q.answer.length);assert.ok(q.answer.every(i=>i>=0&&i<q.options.length));assert.ok(q.lessonIds.every(id=>ids.lessons.has(id)));assert.equal(q.license,'CC-BY-NC-SA-4.0');}
});
test('six routes preserve cumulative round foundations and references',()=>{assert.deepEqual(Object.keys(curriculum.routes),['E1','E2','J1','J2','S1','S2']);for(const [route,list] of Object.entries(curriculum.routes)){assert.equal(new Set(list).size,list.length);assert.ok(list.every(id=>ids.lessons.has(id)));if(route.endsWith('2'))assert.ok(curriculum.routes[route[0]+'1'].every(id=>list.includes(id)));}assert.equal(curriculum.routes.S2.length,38);});
test('all 78 book answers match the appendix G reference keys; each paper totals 100',()=>{
 const keys={E:'A C B D A C B D C A ABD AB ACD ABE ADE ACDE T T F F T F T F F T',J:'B A D C A D B C A D ABDE AC ACD ACD ACE ABCE F T T T F F T T F T',S:'A C B D B C A D B C BD BCD ABC AC AC ABCD T T T F F T T F F F'};
 for(const p of exams.papers){assert.equal(p.minutes,90);assert.equal(p.questionIds.length,26);assert.equal(p.questionIds.reduce((s,id)=>s+questions.get(id).points,0),100);keys[p.id].split(' ').forEach((key,i)=>{const expected=i<16?[...key].map(x=>x.charCodeAt(0)-65):[key==='T'?0:1];assert.deepEqual(questions.get(p.questionIds[i]).answer,expected);});}
});
test('shared and image-dependent materials are retained for independent review',()=>{for(const id of ['book-S-02','book-S-03','book-S-04'])assert.ok(questions.get(id).shared.en.includes('TP=16'));for(const id of ['book-J-09','book-J-10','book-S-06','book-S-14'])assert.ok(questions.get(id).diagram);assert.ok(questions.get('book-S-06').prompt.en.includes(String.raw`y=h_{1}-2h_{2}+4`));assert.ok(questions.get('book-S-14').prompt.en.includes('F→B'));});
test('multiple-select grading requires the exact set regardless of order',()=>{assert.ok(sameAnswer([3,0,1],[0,1,3]));assert.ok(!sameAnswer([0,1],[0,1,3]));const q=questions.get('book-E-11');const a=attempt('practice',[q.id]);a.answers[q.id]=[0,1];assert.equal(grade(a,questions).earned,0);a.answers[q.id]=[3,1,0];assert.equal(grade(a,questions).earned,5);a.answers[q.id]=[0,1,2,3];assert.equal(grade(a,questions).earned,0);});
test('unanswered questions score zero and perfect book answers score 100',()=>{const paper=exams.papers[0],a=attempt('exam',paper.questionIds);assert.equal(grade(a,questions).earned,0);for(const id of paper.questionIds)a.answers[id]=questions.get(id).answer;assert.equal(grade(a,questions).earned,100);});
test('deadline survives backup and expires at the exact boundary',()=>{const state=defaults(),a=attempt('exam');state.active=a;const restored=decodeBackup(encodeBackup(state),ids);assert.equal(restored.active.deadline,a.deadline);assert.equal(expired(a,a.deadline-1),false);assert.equal(expired(a,a.deadline),true);a.submittedAt=a.deadline;assert.equal(expired(a,a.deadline+1),false);});
test('review intervals increase on correct recall and reset after a mistake',()=>{let r;for(const n of [1,3,7,14,30,30]){r=reviewNext(r,true,1000);assert.equal(r.due,1000+n*DAY);}r=reviewNext(r,false,1000);assert.equal(r.stage,0);assert.equal(r.due,1000+DAY);});
test('checking and submission do not double-record a response',()=>{const state=defaults(),q=questions.get('drill-1.1-1');recordResponse(state,q,q.answer,'one',100);recordResponse(state,q,[],'one',200);assert.equal(state.responses.length,1);assert.equal(state.responses[0].correct,true);recordResponse(state,q,[],'two',300);assert.equal(state.responses.length,2);assert.equal(mastery(state,'1.1',questions).percent,0);assert.deepEqual(state.completed,[]);});
test('a complete state round-trips including code, notes, flags, language and active answers',()=>{const state=defaults();state.completed=['1.1'];state.bookmarks=['2.1'];state.notes={'1.1':'<b>raw notes</b> 中文'};state.settings.lang='zh';state.python.drafts.basics='print("你好")';state.python.inputs.basics='5';state.active=attempt();state.active.answers['drill-1.1-1']=[0];state.active.flags['drill-1.1-1']=true;recordResponse(state,questions.get('drill-1.1-1'),[0],state.active.id);assert.deepEqual(decodeBackup(encodeBackup(state),ids),state);});
test('invalid backups reject unknown references, bad answers, versions and prototype keys',()=>{for(const mutate of [s=>s.version=2,s=>s.completed=['unknown'],s=>s.settings.lang='fr',s=>s.settings.dailyGoal=-1,s=>s.reviews.x={stage:0,due:1},s=>s.active={...attempt(),answers:{'drill-1.1-1':[99]}},s=>s.active={...attempt(),deadline:-1},s=>s.notes={'1.1':9},s=>s.python.exercise='unknown',s=>s.responses=[{questionId:'drill-1.1-1',answer:[0],correct:false,at:100,attemptId:'x'}]]){const state=defaults();mutate(state);assert.throws(()=>validateState(state,ids));}assert.throws(()=>decodeBackup('{"app":"CAICP Academy","version":1,"data":{"__proto__":{}}}',ids));assert.throws(()=>decodeBackup('{',ids));assert.throws(()=>decodeBackup(' '.repeat(5*1024*1024+1),ids));});
test('storage failures keep current progress exportable and failed imports do not replace state',()=>{const storage={getItem(){throw Error('disabled');},setItem(){throw Error('full');}};const store=createStore(ids,storage);store.state.notes['1.1']='kept';assert.equal(store.save(),false);assert.equal(store.error,true);assert.equal(decodeBackup(store.export(),ids).notes['1.1'],'kept');assert.throws(()=>store.replace({...defaults(),completed:['bad']}));assert.equal(store.state.notes['1.1'],'kept');});
test('saved state loads successfully from a healthy storage provider',()=>{let text;const storage={getItem(){return text||null;},setItem(k,v){text=v;}};const one=createStore(ids,storage);one.state.bookmarks=['1.1'];one.save();assert.deepEqual(createStore(ids,storage).state.bookmarks,['1.1']);});
test('all four sorting algorithms preserve values and finish sorted',()=>{for(const mode of ['bubble','selection','insertion','merge'])assert.deepEqual(sortingFrames([3,-1,3,0,2],mode).at(-1).values,[-1,0,2,3,3]);});
test('binary search finds values, terminates missing searches and rejects unsorted input',()=>{assert.equal(binaryFrames([2,4,6,8,10],8).at(-1).mid,3);assert.equal(binaryFrames([2,4,6,8,10],7).at(-1).mid,-1);assert.throws(()=>binaryFrames([3,1,2],1));});
test('BFS and recursive DFS match the source graph including cycles',()=>{const edges=[['A','B'],['A','D'],['B','C'],['C','A'],['C','E'],['D','E'],['E','F'],['F','B']];assert.deepEqual(traverse(edges,'A','bfs'),['A','B','D','C','E','F']);assert.deepEqual(traverse(edges,'A','dfs'),['A','B','C','E','F','D']);});
test('metrics distinguish denominators and report undefined cases',()=>{const r=metrics(16,8,4,72);assert.equal(r.accuracy,.88);assert.equal(r.recall,.8);assert.equal(r.precision,2/3);assert.equal(metrics(0,0,0,0).precision,null);});
test('CNN cross-correlation, stride and padding calculations',()=>{const a=[[1,2,3],[4,5,6],[7,8,9]],k=[[1,0],[0,-1]];assert.deepEqual(convolution(a,k),[[-4,-4],[-4,-4]]);assert.equal(convolution(a,k,1,1).length,4);assert.deepEqual(convolution(a,k,2),[[-4]]);});
test('K-means computes centroids and preserves empty centers',()=>{assert.deepEqual(kmeansStep([1,2,8,9],[1,9]).centers,[1.5,8.5]);assert.deepEqual(kmeansStep([1,2],[1,100]).centers,[1.5,100]);});
test('numeric lab inputs reject malformed, oversized and infinite values',()=>{assert.deepEqual(numbers('1, 2, -3'),[1,2,-3]);for(const text of ['NaN','Infinity','10001','a,b'])assert.throws(()=>numbers(text));});

test('every route diagnostic contains twelve unique valid questions',()=>{const lessons=new Map(curriculum.lessons.map(l=>[l.id,l]));for(const route of Object.values(curriculum.routes)){const chosen=diagnosticQuestions(route,lessons);assert.equal(chosen.length,12);assert.equal(new Set(chosen).size,12);assert.ok(chosen.every(id=>questions.has(id)&&questions.get(id).lessonIds.some(l=>route.includes(l))));}});

test('Python worker reports an unavailable runtime instead of leaving execution pending',async()=>{
 const source=readFileSync(new URL('../js/python-worker.js',import.meta.url),'utf8');
 // Node deliberately cannot import the HTTPS runtime: exercise the actual worker's load-error path.
 const worker=new Worker(`const {parentPort}=require('node:worker_threads');global.self={postMessage:m=>parentPort.postMessage(m)};${source};self.onmessage({data:{code:'print(1)',input:'',packages:[]}});`,{eval:true});
 try{const message=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Worker did not report load failure')),5000);worker.on('message',m=>{if(m.type==='error'){clearTimeout(timer);resolve(m);}});worker.on('error',e=>{clearTimeout(timer);reject(e);});});assert.ok(message.message.length);}
 finally{await worker.terminate();}
});
